[package]
name = "rasql-build"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Build script utilities for Rasql"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
