[package]
name = "rasql-traits"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Trait definitions for Rasql generated database types"

[dependencies]
tokio-postgres = { version = "0.7.12", optional = true }

[features]
tokio-postgres = ["dep:tokio-postgres"]
